#!/bin/bash

if [ `date +%H` == "02" ]
then
    	export RAILS_ENV="production"
	echo "Starting cron update" > $OPENSHIFT_DATA_DIR/last_update.log
	echo "Cron update script running..."
	echo "Updating gems..." >> $OPENSHIFT_DATA_DIR/last_update.log
	rake database:update_gems[2] >> $OPENSHIFT_DATA_DIR/last_update.log
	echo "Updating RPMs..." >> $OPENSHIFT_DATA_DIR/last_update.log
	rake database:update_rpms[2] >> $OPENSHIFT_DATA_DIR/last_update.log
	echo "Done!" >> $OPENSHIFT_DATA_DIR/last_update.log
fi
